inherits:
  - duplicated

  - utils:base
  - utils:fix
  - utils:unsafe
pylint:
  disable:
    - too-many-branches

pydocstyle:
  disable:
    - D203 # 1 blank line required before class docstring

pyroma:
  run: true
mypy:
  options:
    python-version: '3.10'
ruff:
  options:
    target-version: py310
