name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

permissions:
  contents: write
  id-token: write

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  build:
    name: Continuous integration
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m pip install --requirement=ci/requirements.txt

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files --color=always
      - run: git diff --exit-code --patch > /tmp/pre-commit.patch; git diff --color; git reset --hard || true
        if: failure()

      - uses: actions/upload-artifact@v4
        with:
          name: Apply pre-commit fix.patch
          path: /tmp/pre-commit.patch
          retention-days: 1
        if: failure()
      - name: Print environment information
        run: c2cciutils-env

      - name: GitHub event
        run: echo ${GITHUB_EVENT} | python3 -m json.tool
        env:
          GITHUB_EVENT: ${{ toJson(github) }}

      - run: pip install --use-pep517 .

      - run: (cd example/; pip freeze)
      - run: (cd example/; poetry build -v)
      - run: unzip example/dist/example-0.1.0-py3-none-any.whl
      - run: cat example-0.1.0.dist-info/METADATA
      - run: "grep 'Requires-Dist: dev_f (==1.2.3.dev4)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: dev_m (>=1.2.0.dev4,<1.3.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: dev_mm (>=1.0.0.dev4,<2.0.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: dev_p (>=1.2.3.dev4,<1.2.4)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: m_f (==1.2)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: m_m (>=1.2,<1.3)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: m_mm (>=1.0,<2.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: m_p (>=1.2,<1.2.1)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: mm_f (==1)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: mm_m (>=1,<1.1)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: mm_mm (>=1,<2)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: mm_p (>=1,<1.0.1)' example-0.1.0.dist-info/METADATA"
      - run: 'grep ''Requires-Dist: optional (>=1.0.0,<2.0.0) ; extra == "all"'' example-0.1.0.dist-info/METADATA'
      - run: "grep 'Requires-Dist: p_f (==1.2.3)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: p_m (>=1.2.0,<1.3.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: p_mm (>=1.0.0,<2.0.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: p_p (>=1.2.3,<1.2.4)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: post_f (==1.2.3.post5)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: post_m (>=1.2.0.post5,<1.3.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: post_mm (>=1.0.0.post5,<2.0.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: post_p (>=1.2.3.post5,<1.2.4)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: present' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: set (==4.5.6)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: t1 (>=1.0.0,<3.0.0)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: t2 (>=1.2.3,<2.4.5)' example-0.1.0.dist-info/METADATA"
      - run: "grep 'Requires-Dist: t3 (>=1.dev0,<3)' example-0.1.0.dist-info/METADATA"

      - run: rm -rf example/dist/example-0.1.0-py3-none-any.whl example-0.1.0.dist-info example/__init__.py

      - run: poetry install
      - run: poetry run prospector --output=pylint

      - name: Init pypi
        run: |-
          echo "[pypi]" > ~/.pypirc
          echo "username = ${{ secrets.PYPI_USERNAME }}" >> ~/.pypirc
          echo "password = ${{ secrets.PYPI_PASSWORD }}" >> ~/.pypirc
        if: startsWith(github.ref, 'refs/tags/')

      - name: Publish PyPI
        run: tag-publish
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
      - run: git diff --exit-code --patch > /tmp/dpkg-versions.patch; git diff --color; git reset --hard || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Update dpkg versions list.patch
          path: /tmp/dpkg-versions.patch
          retention-days: 1
        if: failure()
